# ==============================================================================
# MySQL 8.0.25 远程备份恢复工具配置文件 (rdb/config.yaml)
# ==============================================================================

rdb:
  username: "user"
  password: "password"
  port: 3309
